#!/bin/bash
echo $1 $2
PATH=/bin:/sbin:/usr/local/bin:/usr/bin:/usr/local/apps/bin

pdflatex -jobname=$1 -output-directory=certificates $2
chmod 0755 certificates/$1.pdf
rm -f certificates/$1.aux
rm -f certificates/$1.log